GameId      = "armoredcore6"
DisplayName = "Armored Core VI: Fires of Rubicon"

NexusDomain = "armoredcore6firesofrubiconac6"
SteamAppId  = 1888160

RequiredFiles = ["armoredcore6.exe"]

SaveFolderPattern = "%APPDATA%\\ArmoredCore6\\*"

[[MountPoints]]
Id   = "default"
Name = "Game Root"
Path = ""
