GameId      = "darksouls3"
DisplayName = "Dark Souls III"

NexusDomain = "darksouls3"
SteamAppId  = 374320

RequiredFiles = ["DarkSoulsIII.exe"]

[[MountPoints]]
Id   = "default"
Name = "Game Root"
Path = ""

SaveFolderPattern = "%APPDATA%\\DarkSoulsIII\\*"
