GameId      = "darksoulsremastered"
DisplayName = "Dark Souls: Remastered"

NexusDomain = "darksoulsremastered"
SteamAppId  = 570940

RequiredFiles = ["DarkSoulsRemastered.exe"]

[[MountPoints]]
Id   = "default"
Name = "Game Root"
Path = ""

SaveFolderPattern = "%APPDATA%\\DarkSoulsRemastered\\*"
