GameId      = "liesofp"
DisplayName = "Lies of P"

NexusDomain = "liesofp"
SteamAppId  = 1627720

RequiredFiles = ["LOP.exe"]

# PAK mods go into the ~mods folder.
[[MountPoints]]
Id   = "paks"
Name = "PAK Mods"
Path = "LiesofP\\Content\\Paks\\~mods"

# Some mods install to game root.
[[MountPoints]]
Id   = "root"
Name = "Game Root"
Path = ""

SaveFolderPattern = "%LOCALAPPDATA%\\LiesofP\\Saved\\SaveGames"
