GameId      = "pathfinder_kingmaker"
DisplayName = "Pathfinder: Kingmaker"

NexusDomain = "pathfinderkingmaker"
SteamAppId  = 640820

RequiredFiles = ["Kingmaker.exe"]

# Unity Mod Manager mods go into the Mods subfolder.
[[MountPoints]]
Id   = "mods"
Name = "Mods"
Path = "Mods"

# Some mods install to game root.
[[MountPoints]]
Id   = "root"
Name = "Game Root"
Path = ""

SaveFolderPattern = "%APPDATA%\\unity3d\\Owlcat Games\\Pathfinder Kingmaker"
