GameId      = "re_village"
DisplayName = "Resident Evil Village"

NexusDomain = "residentevilvillage"
SteamAppId  = 1196590

RequiredFiles = ["re8.exe"]

[[MountPoints]]
Id   = "default"
Name = "Game Root"
Path = ""

SaveFolderPattern = "%APPDATA%\\RE8"
