GameId      = "re_village"
DisplayName = "Resident Evil Village"

NexusDomain = "residentevilvillage"
SteamAppId  = 1196590

RequiredFiles = ["re8.exe"]

DataSubFolder = ""
RootSwapOnly  = true

SaveFolderPattern = "%APPDATA%\RE8"
