GameId      = "sekiro"
DisplayName = "Sekiro: Shadows Die Twice"

NexusDomain = "sekiro"
SteamAppId  = 814380

RequiredFiles = ["sekiro.exe"]

[[MountPoints]]
Id   = "default"
Name = "Game Root"
Path = ""

SaveFolderPattern = "%APPDATA%\\Sekiro\\*"
